---
queries:
  - query: |
      CREATE TABLE IF NOT EXISTS secrets (
        key VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
        value VARCHAR(4096) NOT NULL,
        username VARCHAR(255),
        uri VARCHAR(1024),
        notes VARCHAR(4096),
        type VARCHAR(8)
      )
# inline queries
insert_secret: INSERT INTO secrets (key, value, username, uri, notes, type) VALUES($1, $2, $3, $4, $5, $6)
delete_secret: DELETE FROM secrets WHERE key=$1
select_secrets: SELECT key, value, username, uri, notes FROM secrets
select_secret: SELECT key, value, username, uri, notes FROM secrets WHERE key=$1
update_secret: UPDATE secrets SET value=$2, username=$3, uri=$4, notes=$5 WHERE key=$1
drop_secrets: DROP TABLE secrets
